<?php

/* custom routes generated by CRUD */
Route::group(array('prefix' => 'admin', 'middleware' => ['web','SentinelAdmin']), function () {
	Route::resource('events', 'EventsController');
	Route::get('events/{id}/delete', array('as' => 'admin.events.delete', 'uses' => 'EventsController@getDelete'));
	Route::get('events/{id}/confirm-delete', array('as' => 'admin.events.confirm-delete', 'uses' => 'EventsController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => ['web','SentinelAdmin']), function () {Route::resource('ads', 'AdsController');
	Route::get('ads/{id}/delete', array('as' => 'admin.ads.delete', 'uses' => 'AdsController@getDelete'));
	Route::get('ads/{id}/confirm-delete', array('as' => 'admin.ads.confirm-delete', 'uses' => 'AdsController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => ['web','SentinelAdmin']), function () {Route::resource('resources', 'ResourcesController');
	Route::get('resources/{id}/delete', array('as' => 'admin.resources.delete', 'uses' => 'ResourcesController@getDelete'));
	Route::get('resources/{id}/confirm-delete', array('as' => 'admin.resources.confirm-delete', 'uses' => 'ResourcesController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => ['web','SentinelAdmin']), function () {Route::resource('pages', 'PagesController');
	Route::get('pages/{id}/delete', array('as' => 'admin.pages.delete', 'uses' => 'PagesController@getDelete'));
	Route::get('pages/{id}/confirm-delete', array('as' => 'admin.pages.confirm-delete', 'uses' => 'PagesController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => ['web','SentinelAdmin']), function () {Route::resource('bookings', 'BookingsController');
	Route::get('bookings/{id}/delete', array('as' => 'admin.bookings.delete', 'uses' => 'BookingsController@getDelete'));
	Route::get('bookings/{id}/confirm-delete', array('as' => 'admin.bookings.confirm-delete', 'uses' => 'BookingsController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => ['web','SentinelAdmin']), function () {Route::resource('ads_categories', 'Ads_categoriesController');
	Route::get('ads_categories/{id}/delete', array('as' => 'admin.ads_categories.delete', 'uses' => 'Ads_categoriesController@getDelete'));
	Route::get('ads_categories/{id}/confirm-delete', array('as' => 'admin.ads_categories.confirm-delete', 'uses' => 'Ads_categoriesController@getModalDelete'));
});